// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlstore

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getBlobRefsByScopeAnd100RefsStmt, err = db.PrepareContext(ctx, getBlobRefsByScopeAnd100Refs); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlobRefsByScopeAnd100Refs: %w", err)
	}
	if q.getBlobRefsByScopeAnd10RefsStmt, err = db.PrepareContext(ctx, getBlobRefsByScopeAnd10Refs); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlobRefsByScopeAnd10Refs: %w", err)
	}
	if q.getBlobValuesByRefStmt, err = db.PrepareContext(ctx, getBlobValuesByRef); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlobValuesByRef: %w", err)
	}
	if q.getBlobValuesByScopeStmt, err = db.PrepareContext(ctx, getBlobValuesByScope); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlobValuesByScope: %w", err)
	}
	if q.insertBlobRefStmt, err = db.PrepareContext(ctx, insertBlobRef); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBlobRef: %w", err)
	}
	if q.upsertBlobStmt, err = db.PrepareContext(ctx, upsertBlob); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertBlob: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getBlobRefsByScopeAnd100RefsStmt != nil {
		if cerr := q.getBlobRefsByScopeAnd100RefsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlobRefsByScopeAnd100RefsStmt: %w", cerr)
		}
	}
	if q.getBlobRefsByScopeAnd10RefsStmt != nil {
		if cerr := q.getBlobRefsByScopeAnd10RefsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlobRefsByScopeAnd10RefsStmt: %w", cerr)
		}
	}
	if q.getBlobValuesByRefStmt != nil {
		if cerr := q.getBlobValuesByRefStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlobValuesByRefStmt: %w", cerr)
		}
	}
	if q.getBlobValuesByScopeStmt != nil {
		if cerr := q.getBlobValuesByScopeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlobValuesByScopeStmt: %w", cerr)
		}
	}
	if q.insertBlobRefStmt != nil {
		if cerr := q.insertBlobRefStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBlobRefStmt: %w", cerr)
		}
	}
	if q.upsertBlobStmt != nil {
		if cerr := q.upsertBlobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertBlobStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	getBlobRefsByScopeAnd100RefsStmt *sql.Stmt
	getBlobRefsByScopeAnd10RefsStmt  *sql.Stmt
	getBlobValuesByRefStmt           *sql.Stmt
	getBlobValuesByScopeStmt         *sql.Stmt
	insertBlobRefStmt                *sql.Stmt
	upsertBlobStmt                   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		getBlobRefsByScopeAnd100RefsStmt: q.getBlobRefsByScopeAnd100RefsStmt,
		getBlobRefsByScopeAnd10RefsStmt:  q.getBlobRefsByScopeAnd10RefsStmt,
		getBlobValuesByRefStmt:           q.getBlobValuesByRefStmt,
		getBlobValuesByScopeStmt:         q.getBlobValuesByScopeStmt,
		insertBlobRefStmt:                q.insertBlobRefStmt,
		upsertBlobStmt:                   q.upsertBlobStmt,
	}
}
