// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlstore

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countBlobEntriesByFilterStmt, err = db.PrepareContext(ctx, countBlobEntriesByFilter); err != nil {
		return nil, fmt.Errorf("error preparing query CountBlobEntriesByFilter: %w", err)
	}
	if q.deleteBlobByBlobKeyStmt, err = db.PrepareContext(ctx, deleteBlobByBlobKey); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBlobByBlobKey: %w", err)
	}
	if q.deleteBlobsByFilterStmt, err = db.PrepareContext(ctx, deleteBlobsByFilter); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBlobsByFilter: %w", err)
	}
	if q.getBlobIDByBlobKeyStmt, err = db.PrepareContext(ctx, getBlobIDByBlobKey); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlobIDByBlobKey: %w", err)
	}
	if q.getBlobValuesByFilterStmt, err = db.PrepareContext(ctx, getBlobValuesByFilter); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlobValuesByFilter: %w", err)
	}
	if q.insertBlobEntriesByScopeAnd100EntriesStmt, err = db.PrepareContext(ctx, insertBlobEntriesByScopeAnd100Entries); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBlobEntriesByScopeAnd100Entries: %w", err)
	}
	if q.insertBlobEntriesByScopeAnd10EntriesStmt, err = db.PrepareContext(ctx, insertBlobEntriesByScopeAnd10Entries); err != nil {
		return nil, fmt.Errorf("error preparing query InsertBlobEntriesByScopeAnd10Entries: %w", err)
	}
	if q.updateBlobValueStmt, err = db.PrepareContext(ctx, updateBlobValue); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBlobValue: %w", err)
	}
	if q.upsertBlobStmt, err = db.PrepareContext(ctx, upsertBlob); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertBlob: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countBlobEntriesByFilterStmt != nil {
		if cerr := q.countBlobEntriesByFilterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countBlobEntriesByFilterStmt: %w", cerr)
		}
	}
	if q.deleteBlobByBlobKeyStmt != nil {
		if cerr := q.deleteBlobByBlobKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBlobByBlobKeyStmt: %w", cerr)
		}
	}
	if q.deleteBlobsByFilterStmt != nil {
		if cerr := q.deleteBlobsByFilterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBlobsByFilterStmt: %w", cerr)
		}
	}
	if q.getBlobIDByBlobKeyStmt != nil {
		if cerr := q.getBlobIDByBlobKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlobIDByBlobKeyStmt: %w", cerr)
		}
	}
	if q.getBlobValuesByFilterStmt != nil {
		if cerr := q.getBlobValuesByFilterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlobValuesByFilterStmt: %w", cerr)
		}
	}
	if q.insertBlobEntriesByScopeAnd100EntriesStmt != nil {
		if cerr := q.insertBlobEntriesByScopeAnd100EntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBlobEntriesByScopeAnd100EntriesStmt: %w", cerr)
		}
	}
	if q.insertBlobEntriesByScopeAnd10EntriesStmt != nil {
		if cerr := q.insertBlobEntriesByScopeAnd10EntriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertBlobEntriesByScopeAnd10EntriesStmt: %w", cerr)
		}
	}
	if q.updateBlobValueStmt != nil {
		if cerr := q.updateBlobValueStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBlobValueStmt: %w", cerr)
		}
	}
	if q.upsertBlobStmt != nil {
		if cerr := q.upsertBlobStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertBlobStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                        DBTX
	tx                                        *sql.Tx
	countBlobEntriesByFilterStmt              *sql.Stmt
	deleteBlobByBlobKeyStmt                   *sql.Stmt
	deleteBlobsByFilterStmt                   *sql.Stmt
	getBlobIDByBlobKeyStmt                    *sql.Stmt
	getBlobValuesByFilterStmt                 *sql.Stmt
	insertBlobEntriesByScopeAnd100EntriesStmt *sql.Stmt
	insertBlobEntriesByScopeAnd10EntriesStmt  *sql.Stmt
	updateBlobValueStmt                       *sql.Stmt
	upsertBlobStmt                            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		countBlobEntriesByFilterStmt: q.countBlobEntriesByFilterStmt,
		deleteBlobByBlobKeyStmt:      q.deleteBlobByBlobKeyStmt,
		deleteBlobsByFilterStmt:      q.deleteBlobsByFilterStmt,
		getBlobIDByBlobKeyStmt:       q.getBlobIDByBlobKeyStmt,
		getBlobValuesByFilterStmt:    q.getBlobValuesByFilterStmt,
		insertBlobEntriesByScopeAnd100EntriesStmt: q.insertBlobEntriesByScopeAnd100EntriesStmt,
		insertBlobEntriesByScopeAnd10EntriesStmt:  q.insertBlobEntriesByScopeAnd10EntriesStmt,
		updateBlobValueStmt:                       q.updateBlobValueStmt,
		upsertBlobStmt:                            q.upsertBlobStmt,
	}
}
