// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlstore

type Blob struct {
	BlobID    int64  `db:"blob_id"`
	BlobKey   string `db:"blob_key"`
	BlobValue []byte `db:"blob_value"`
	UpdatedAt int64  `db:"updated_at"`
}

type BlobEntry struct {
	Namespace string `db:"namespace"`
	Subject   int64  `db:"subject"`
	ID        int64  `db:"id"`
	MetaTag   string `db:"meta_tag"`
	BlobID    int64  `db:"blob_id"`
}
