// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlstore

import (
	"context"
)

const getBlobValuesByIdentity = `-- name: GetBlobValuesByIdentity :many
SELECT DISTINCT b.blob_id, b.blob_key, b.blob_value
FROM blob_entries br
JOIN blobs b ON b.blob_id = br.blob_id
WHERE br.namespace = ?1
  AND br.subject = ?2
  AND br.id = ?3
  AND br.meta_tag = ?4
`

type GetBlobValuesByIdentityParams struct {
	Namespace string `db:"namespace"`
	Subject   int64  `db:"subject"`
	ID        int64  `db:"id"`
	MetaTag   string `db:"meta_tag"`
}

type GetBlobValuesByIdentityRow struct {
	BlobID    int64  `db:"blob_id"`
	BlobKey   string `db:"blob_key"`
	BlobValue []byte `db:"blob_value"`
}

func (q *Queries) GetBlobValuesByIdentity(ctx context.Context, arg GetBlobValuesByIdentityParams) ([]GetBlobValuesByIdentityRow, error) {
	rows, err := q.query(ctx, q.getBlobValuesByIdentityStmt, getBlobValuesByIdentity,
		arg.Namespace,
		arg.Subject,
		arg.ID,
		arg.MetaTag,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlobValuesByIdentityRow{}
	for rows.Next() {
		var i GetBlobValuesByIdentityRow
		if err := rows.Scan(&i.BlobID, &i.BlobKey, &i.BlobValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlobValuesByScope = `-- name: GetBlobValuesByScope :many
SELECT DISTINCT b.blob_id, b.blob_key, b.blob_value
FROM blob_entries br
JOIN blobs b ON b.blob_id = br.blob_id
WHERE br.namespace = ?1
  AND br.subject = ?2
`

type GetBlobValuesByScopeParams struct {
	Namespace string `db:"namespace"`
	Subject   int64  `db:"subject"`
}

type GetBlobValuesByScopeRow struct {
	BlobID    int64  `db:"blob_id"`
	BlobKey   string `db:"blob_key"`
	BlobValue []byte `db:"blob_value"`
}

func (q *Queries) GetBlobValuesByScope(ctx context.Context, arg GetBlobValuesByScopeParams) ([]GetBlobValuesByScopeRow, error) {
	rows, err := q.query(ctx, q.getBlobValuesByScopeStmt, getBlobValuesByScope, arg.Namespace, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlobValuesByScopeRow{}
	for rows.Next() {
		var i GetBlobValuesByScopeRow
		if err := rows.Scan(&i.BlobID, &i.BlobKey, &i.BlobValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBlobEntry = `-- name: InsertBlobEntry :exec
INSERT INTO blob_entries (
    namespace,
    subject,
    id,
    meta_tag,
    blob_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type InsertBlobEntryParams struct {
	Namespace string `db:"namespace"`
	Subject   int64  `db:"subject"`
	ID        int64  `db:"id"`
	MetaTag   string `db:"meta_tag"`
	BlobID    int64  `db:"blob_id"`
}

func (q *Queries) InsertBlobEntry(ctx context.Context, arg InsertBlobEntryParams) error {
	_, err := q.exec(ctx, q.insertBlobEntryStmt, insertBlobEntry,
		arg.Namespace,
		arg.Subject,
		arg.ID,
		arg.MetaTag,
		arg.BlobID,
	)
	return err
}

const updateBlobValue = `-- name: UpdateBlobValue :exec
UPDATE blobs
SET blob_key = ?1,
    blob_value = ?2,
    updated_at = ?3
WHERE blob_id = ?4
`

type UpdateBlobValueParams struct {
	BlobKey   string `db:"blob_key"`
	BlobValue []byte `db:"blob_value"`
	UpdatedAt int64  `db:"updated_at"`
	BlobID    int64  `db:"blob_id"`
}

func (q *Queries) UpdateBlobValue(ctx context.Context, arg UpdateBlobValueParams) error {
	_, err := q.exec(ctx, q.updateBlobValueStmt, updateBlobValue,
		arg.BlobKey,
		arg.BlobValue,
		arg.UpdatedAt,
		arg.BlobID,
	)
	return err
}

const upsertBlob = `-- name: UpsertBlob :one
INSERT INTO blobs (
    blob_key,
    blob_value,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3
)
ON CONFLICT(blob_key) DO UPDATE SET
    blob_value = excluded.blob_value,
    updated_at = excluded.updated_at
RETURNING blob_id
`

type UpsertBlobParams struct {
	BlobKey   string `db:"blob_key"`
	BlobValue []byte `db:"blob_value"`
	UpdatedAt int64  `db:"updated_at"`
}

func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) (int64, error) {
	row := q.queryRow(ctx, q.upsertBlobStmt, upsertBlob, arg.BlobKey, arg.BlobValue, arg.UpdatedAt)
	var blob_id int64
	err := row.Scan(&blob_id)
	return blob_id, err
}
