// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_blob_batch.sql

package sqlstore

import (
	"context"
)

const getBlobEntriesByScopeAnd100Entries = `-- name: GetBlobEntriesByScopeAnd100Entries :many
WITH entries(id, meta_tag) AS (
  SELECT ?3 AS id, ?4 AS meta_tag
  UNION ALL SELECT ?5 AS id, ?6 AS meta_tag
  UNION ALL SELECT ?7 AS id, ?8 AS meta_tag
  UNION ALL SELECT ?9 AS id, ?10 AS meta_tag
  UNION ALL SELECT ?11 AS id, ?12 AS meta_tag
  UNION ALL SELECT ?13 AS id, ?14 AS meta_tag
  UNION ALL SELECT ?15 AS id, ?16 AS meta_tag
  UNION ALL SELECT ?17 AS id, ?18 AS meta_tag
  UNION ALL SELECT ?19 AS id, ?20 AS meta_tag
  UNION ALL SELECT ?21 AS id, ?22 AS meta_tag
  UNION ALL SELECT ?23 AS id, ?24 AS meta_tag
  UNION ALL SELECT ?25 AS id, ?26 AS meta_tag
  UNION ALL SELECT ?27 AS id, ?28 AS meta_tag
  UNION ALL SELECT ?29 AS id, ?30 AS meta_tag
  UNION ALL SELECT ?31 AS id, ?32 AS meta_tag
  UNION ALL SELECT ?33 AS id, ?34 AS meta_tag
  UNION ALL SELECT ?35 AS id, ?36 AS meta_tag
  UNION ALL SELECT ?37 AS id, ?38 AS meta_tag
  UNION ALL SELECT ?39 AS id, ?40 AS meta_tag
  UNION ALL SELECT ?41 AS id, ?42 AS meta_tag
  UNION ALL SELECT ?43 AS id, ?44 AS meta_tag
  UNION ALL SELECT ?45 AS id, ?46 AS meta_tag
  UNION ALL SELECT ?47 AS id, ?48 AS meta_tag
  UNION ALL SELECT ?49 AS id, ?50 AS meta_tag
  UNION ALL SELECT ?51 AS id, ?52 AS meta_tag
  UNION ALL SELECT ?53 AS id, ?54 AS meta_tag
  UNION ALL SELECT ?55 AS id, ?56 AS meta_tag
  UNION ALL SELECT ?57 AS id, ?58 AS meta_tag
  UNION ALL SELECT ?59 AS id, ?60 AS meta_tag
  UNION ALL SELECT ?61 AS id, ?62 AS meta_tag
  UNION ALL SELECT ?63 AS id, ?64 AS meta_tag
  UNION ALL SELECT ?65 AS id, ?66 AS meta_tag
  UNION ALL SELECT ?67 AS id, ?68 AS meta_tag
  UNION ALL SELECT ?69 AS id, ?70 AS meta_tag
  UNION ALL SELECT ?71 AS id, ?72 AS meta_tag
  UNION ALL SELECT ?73 AS id, ?74 AS meta_tag
  UNION ALL SELECT ?75 AS id, ?76 AS meta_tag
  UNION ALL SELECT ?77 AS id, ?78 AS meta_tag
  UNION ALL SELECT ?79 AS id, ?80 AS meta_tag
  UNION ALL SELECT ?81 AS id, ?82 AS meta_tag
  UNION ALL SELECT ?83 AS id, ?84 AS meta_tag
  UNION ALL SELECT ?85 AS id, ?86 AS meta_tag
  UNION ALL SELECT ?87 AS id, ?88 AS meta_tag
  UNION ALL SELECT ?89 AS id, ?90 AS meta_tag
  UNION ALL SELECT ?91 AS id, ?92 AS meta_tag
  UNION ALL SELECT ?93 AS id, ?94 AS meta_tag
  UNION ALL SELECT ?95 AS id, ?96 AS meta_tag
  UNION ALL SELECT ?97 AS id, ?98 AS meta_tag
  UNION ALL SELECT ?99 AS id, ?100 AS meta_tag
  UNION ALL SELECT ?101 AS id, ?102 AS meta_tag
  UNION ALL SELECT ?103 AS id, ?104 AS meta_tag
  UNION ALL SELECT ?105 AS id, ?106 AS meta_tag
  UNION ALL SELECT ?107 AS id, ?108 AS meta_tag
  UNION ALL SELECT ?109 AS id, ?110 AS meta_tag
  UNION ALL SELECT ?111 AS id, ?112 AS meta_tag
  UNION ALL SELECT ?113 AS id, ?114 AS meta_tag
  UNION ALL SELECT ?115 AS id, ?116 AS meta_tag
  UNION ALL SELECT ?117 AS id, ?118 AS meta_tag
  UNION ALL SELECT ?119 AS id, ?120 AS meta_tag
  UNION ALL SELECT ?121 AS id, ?122 AS meta_tag
  UNION ALL SELECT ?123 AS id, ?124 AS meta_tag
  UNION ALL SELECT ?125 AS id, ?126 AS meta_tag
  UNION ALL SELECT ?127 AS id, ?128 AS meta_tag
  UNION ALL SELECT ?129 AS id, ?130 AS meta_tag
  UNION ALL SELECT ?131 AS id, ?132 AS meta_tag
  UNION ALL SELECT ?133 AS id, ?134 AS meta_tag
  UNION ALL SELECT ?135 AS id, ?136 AS meta_tag
  UNION ALL SELECT ?137 AS id, ?138 AS meta_tag
  UNION ALL SELECT ?139 AS id, ?140 AS meta_tag
  UNION ALL SELECT ?141 AS id, ?142 AS meta_tag
  UNION ALL SELECT ?143 AS id, ?144 AS meta_tag
  UNION ALL SELECT ?145 AS id, ?146 AS meta_tag
  UNION ALL SELECT ?147 AS id, ?148 AS meta_tag
  UNION ALL SELECT ?149 AS id, ?150 AS meta_tag
  UNION ALL SELECT ?151 AS id, ?152 AS meta_tag
  UNION ALL SELECT ?153 AS id, ?154 AS meta_tag
  UNION ALL SELECT ?155 AS id, ?156 AS meta_tag
  UNION ALL SELECT ?157 AS id, ?158 AS meta_tag
  UNION ALL SELECT ?159 AS id, ?160 AS meta_tag
  UNION ALL SELECT ?161 AS id, ?162 AS meta_tag
  UNION ALL SELECT ?163 AS id, ?164 AS meta_tag
  UNION ALL SELECT ?165 AS id, ?166 AS meta_tag
  UNION ALL SELECT ?167 AS id, ?168 AS meta_tag
  UNION ALL SELECT ?169 AS id, ?170 AS meta_tag
  UNION ALL SELECT ?171 AS id, ?172 AS meta_tag
  UNION ALL SELECT ?173 AS id, ?174 AS meta_tag
  UNION ALL SELECT ?175 AS id, ?176 AS meta_tag
  UNION ALL SELECT ?177 AS id, ?178 AS meta_tag
  UNION ALL SELECT ?179 AS id, ?180 AS meta_tag
  UNION ALL SELECT ?181 AS id, ?182 AS meta_tag
  UNION ALL SELECT ?183 AS id, ?184 AS meta_tag
  UNION ALL SELECT ?185 AS id, ?186 AS meta_tag
  UNION ALL SELECT ?187 AS id, ?188 AS meta_tag
  UNION ALL SELECT ?189 AS id, ?190 AS meta_tag
  UNION ALL SELECT ?191 AS id, ?192 AS meta_tag
  UNION ALL SELECT ?193 AS id, ?194 AS meta_tag
  UNION ALL SELECT ?195 AS id, ?196 AS meta_tag
  UNION ALL SELECT ?197 AS id, ?198 AS meta_tag
  UNION ALL SELECT ?199 AS id, ?200 AS meta_tag
  UNION ALL SELECT ?201 AS id, ?202 AS meta_tag
)
SELECT DISTINCT be.blob_id
FROM entries e
JOIN blob_entries be
  ON be.id = e.id
 AND be.meta_tag = e.meta_tag
WHERE be.namespace = ?1
  AND be.subject = ?2
  -- Both checks are intentionally redundant: caller promises entries are all-null or all-non-null pairs.
  AND e.id IS NOT NULL
  AND e.meta_tag IS NOT NULL
`

type GetBlobEntriesByScopeAnd100EntriesParams struct {
	Namespace string  `db:"namespace"`
	Subject   int64   `db:"subject"`
	ID00      *int64  `db:"id_00"`
	MetaTag00 *string `db:"meta_tag_00"`
	ID01      *int64  `db:"id_01"`
	MetaTag01 *string `db:"meta_tag_01"`
	ID02      *int64  `db:"id_02"`
	MetaTag02 *string `db:"meta_tag_02"`
	ID03      *int64  `db:"id_03"`
	MetaTag03 *string `db:"meta_tag_03"`
	ID04      *int64  `db:"id_04"`
	MetaTag04 *string `db:"meta_tag_04"`
	ID05      *int64  `db:"id_05"`
	MetaTag05 *string `db:"meta_tag_05"`
	ID06      *int64  `db:"id_06"`
	MetaTag06 *string `db:"meta_tag_06"`
	ID07      *int64  `db:"id_07"`
	MetaTag07 *string `db:"meta_tag_07"`
	ID08      *int64  `db:"id_08"`
	MetaTag08 *string `db:"meta_tag_08"`
	ID09      *int64  `db:"id_09"`
	MetaTag09 *string `db:"meta_tag_09"`
	ID10      *int64  `db:"id_10"`
	MetaTag10 *string `db:"meta_tag_10"`
	ID11      *int64  `db:"id_11"`
	MetaTag11 *string `db:"meta_tag_11"`
	ID12      *int64  `db:"id_12"`
	MetaTag12 *string `db:"meta_tag_12"`
	ID13      *int64  `db:"id_13"`
	MetaTag13 *string `db:"meta_tag_13"`
	ID14      *int64  `db:"id_14"`
	MetaTag14 *string `db:"meta_tag_14"`
	ID15      *int64  `db:"id_15"`
	MetaTag15 *string `db:"meta_tag_15"`
	ID16      *int64  `db:"id_16"`
	MetaTag16 *string `db:"meta_tag_16"`
	ID17      *int64  `db:"id_17"`
	MetaTag17 *string `db:"meta_tag_17"`
	ID18      *int64  `db:"id_18"`
	MetaTag18 *string `db:"meta_tag_18"`
	ID19      *int64  `db:"id_19"`
	MetaTag19 *string `db:"meta_tag_19"`
	ID20      *int64  `db:"id_20"`
	MetaTag20 *string `db:"meta_tag_20"`
	ID21      *int64  `db:"id_21"`
	MetaTag21 *string `db:"meta_tag_21"`
	ID22      *int64  `db:"id_22"`
	MetaTag22 *string `db:"meta_tag_22"`
	ID23      *int64  `db:"id_23"`
	MetaTag23 *string `db:"meta_tag_23"`
	ID24      *int64  `db:"id_24"`
	MetaTag24 *string `db:"meta_tag_24"`
	ID25      *int64  `db:"id_25"`
	MetaTag25 *string `db:"meta_tag_25"`
	ID26      *int64  `db:"id_26"`
	MetaTag26 *string `db:"meta_tag_26"`
	ID27      *int64  `db:"id_27"`
	MetaTag27 *string `db:"meta_tag_27"`
	ID28      *int64  `db:"id_28"`
	MetaTag28 *string `db:"meta_tag_28"`
	ID29      *int64  `db:"id_29"`
	MetaTag29 *string `db:"meta_tag_29"`
	ID30      *int64  `db:"id_30"`
	MetaTag30 *string `db:"meta_tag_30"`
	ID31      *int64  `db:"id_31"`
	MetaTag31 *string `db:"meta_tag_31"`
	ID32      *int64  `db:"id_32"`
	MetaTag32 *string `db:"meta_tag_32"`
	ID33      *int64  `db:"id_33"`
	MetaTag33 *string `db:"meta_tag_33"`
	ID34      *int64  `db:"id_34"`
	MetaTag34 *string `db:"meta_tag_34"`
	ID35      *int64  `db:"id_35"`
	MetaTag35 *string `db:"meta_tag_35"`
	ID36      *int64  `db:"id_36"`
	MetaTag36 *string `db:"meta_tag_36"`
	ID37      *int64  `db:"id_37"`
	MetaTag37 *string `db:"meta_tag_37"`
	ID38      *int64  `db:"id_38"`
	MetaTag38 *string `db:"meta_tag_38"`
	ID39      *int64  `db:"id_39"`
	MetaTag39 *string `db:"meta_tag_39"`
	ID40      *int64  `db:"id_40"`
	MetaTag40 *string `db:"meta_tag_40"`
	ID41      *int64  `db:"id_41"`
	MetaTag41 *string `db:"meta_tag_41"`
	ID42      *int64  `db:"id_42"`
	MetaTag42 *string `db:"meta_tag_42"`
	ID43      *int64  `db:"id_43"`
	MetaTag43 *string `db:"meta_tag_43"`
	ID44      *int64  `db:"id_44"`
	MetaTag44 *string `db:"meta_tag_44"`
	ID45      *int64  `db:"id_45"`
	MetaTag45 *string `db:"meta_tag_45"`
	ID46      *int64  `db:"id_46"`
	MetaTag46 *string `db:"meta_tag_46"`
	ID47      *int64  `db:"id_47"`
	MetaTag47 *string `db:"meta_tag_47"`
	ID48      *int64  `db:"id_48"`
	MetaTag48 *string `db:"meta_tag_48"`
	ID49      *int64  `db:"id_49"`
	MetaTag49 *string `db:"meta_tag_49"`
	ID50      *int64  `db:"id_50"`
	MetaTag50 *string `db:"meta_tag_50"`
	ID51      *int64  `db:"id_51"`
	MetaTag51 *string `db:"meta_tag_51"`
	ID52      *int64  `db:"id_52"`
	MetaTag52 *string `db:"meta_tag_52"`
	ID53      *int64  `db:"id_53"`
	MetaTag53 *string `db:"meta_tag_53"`
	ID54      *int64  `db:"id_54"`
	MetaTag54 *string `db:"meta_tag_54"`
	ID55      *int64  `db:"id_55"`
	MetaTag55 *string `db:"meta_tag_55"`
	ID56      *int64  `db:"id_56"`
	MetaTag56 *string `db:"meta_tag_56"`
	ID57      *int64  `db:"id_57"`
	MetaTag57 *string `db:"meta_tag_57"`
	ID58      *int64  `db:"id_58"`
	MetaTag58 *string `db:"meta_tag_58"`
	ID59      *int64  `db:"id_59"`
	MetaTag59 *string `db:"meta_tag_59"`
	ID60      *int64  `db:"id_60"`
	MetaTag60 *string `db:"meta_tag_60"`
	ID61      *int64  `db:"id_61"`
	MetaTag61 *string `db:"meta_tag_61"`
	ID62      *int64  `db:"id_62"`
	MetaTag62 *string `db:"meta_tag_62"`
	ID63      *int64  `db:"id_63"`
	MetaTag63 *string `db:"meta_tag_63"`
	ID64      *int64  `db:"id_64"`
	MetaTag64 *string `db:"meta_tag_64"`
	ID65      *int64  `db:"id_65"`
	MetaTag65 *string `db:"meta_tag_65"`
	ID66      *int64  `db:"id_66"`
	MetaTag66 *string `db:"meta_tag_66"`
	ID67      *int64  `db:"id_67"`
	MetaTag67 *string `db:"meta_tag_67"`
	ID68      *int64  `db:"id_68"`
	MetaTag68 *string `db:"meta_tag_68"`
	ID69      *int64  `db:"id_69"`
	MetaTag69 *string `db:"meta_tag_69"`
	ID70      *int64  `db:"id_70"`
	MetaTag70 *string `db:"meta_tag_70"`
	ID71      *int64  `db:"id_71"`
	MetaTag71 *string `db:"meta_tag_71"`
	ID72      *int64  `db:"id_72"`
	MetaTag72 *string `db:"meta_tag_72"`
	ID73      *int64  `db:"id_73"`
	MetaTag73 *string `db:"meta_tag_73"`
	ID74      *int64  `db:"id_74"`
	MetaTag74 *string `db:"meta_tag_74"`
	ID75      *int64  `db:"id_75"`
	MetaTag75 *string `db:"meta_tag_75"`
	ID76      *int64  `db:"id_76"`
	MetaTag76 *string `db:"meta_tag_76"`
	ID77      *int64  `db:"id_77"`
	MetaTag77 *string `db:"meta_tag_77"`
	ID78      *int64  `db:"id_78"`
	MetaTag78 *string `db:"meta_tag_78"`
	ID79      *int64  `db:"id_79"`
	MetaTag79 *string `db:"meta_tag_79"`
	ID80      *int64  `db:"id_80"`
	MetaTag80 *string `db:"meta_tag_80"`
	ID81      *int64  `db:"id_81"`
	MetaTag81 *string `db:"meta_tag_81"`
	ID82      *int64  `db:"id_82"`
	MetaTag82 *string `db:"meta_tag_82"`
	ID83      *int64  `db:"id_83"`
	MetaTag83 *string `db:"meta_tag_83"`
	ID84      *int64  `db:"id_84"`
	MetaTag84 *string `db:"meta_tag_84"`
	ID85      *int64  `db:"id_85"`
	MetaTag85 *string `db:"meta_tag_85"`
	ID86      *int64  `db:"id_86"`
	MetaTag86 *string `db:"meta_tag_86"`
	ID87      *int64  `db:"id_87"`
	MetaTag87 *string `db:"meta_tag_87"`
	ID88      *int64  `db:"id_88"`
	MetaTag88 *string `db:"meta_tag_88"`
	ID89      *int64  `db:"id_89"`
	MetaTag89 *string `db:"meta_tag_89"`
	ID90      *int64  `db:"id_90"`
	MetaTag90 *string `db:"meta_tag_90"`
	ID91      *int64  `db:"id_91"`
	MetaTag91 *string `db:"meta_tag_91"`
	ID92      *int64  `db:"id_92"`
	MetaTag92 *string `db:"meta_tag_92"`
	ID93      *int64  `db:"id_93"`
	MetaTag93 *string `db:"meta_tag_93"`
	ID94      *int64  `db:"id_94"`
	MetaTag94 *string `db:"meta_tag_94"`
	ID95      *int64  `db:"id_95"`
	MetaTag95 *string `db:"meta_tag_95"`
	ID96      *int64  `db:"id_96"`
	MetaTag96 *string `db:"meta_tag_96"`
	ID97      *int64  `db:"id_97"`
	MetaTag97 *string `db:"meta_tag_97"`
	ID98      *int64  `db:"id_98"`
	MetaTag98 *string `db:"meta_tag_98"`
	ID99      *int64  `db:"id_99"`
	MetaTag99 *string `db:"meta_tag_99"`
}

func (q *Queries) GetBlobEntriesByScopeAnd100Entries(ctx context.Context, arg GetBlobEntriesByScopeAnd100EntriesParams) ([]int64, error) {
	rows, err := q.query(ctx, q.getBlobEntriesByScopeAnd100EntriesStmt, getBlobEntriesByScopeAnd100Entries,
		arg.Namespace,
		arg.Subject,
		arg.ID00,
		arg.MetaTag00,
		arg.ID01,
		arg.MetaTag01,
		arg.ID02,
		arg.MetaTag02,
		arg.ID03,
		arg.MetaTag03,
		arg.ID04,
		arg.MetaTag04,
		arg.ID05,
		arg.MetaTag05,
		arg.ID06,
		arg.MetaTag06,
		arg.ID07,
		arg.MetaTag07,
		arg.ID08,
		arg.MetaTag08,
		arg.ID09,
		arg.MetaTag09,
		arg.ID10,
		arg.MetaTag10,
		arg.ID11,
		arg.MetaTag11,
		arg.ID12,
		arg.MetaTag12,
		arg.ID13,
		arg.MetaTag13,
		arg.ID14,
		arg.MetaTag14,
		arg.ID15,
		arg.MetaTag15,
		arg.ID16,
		arg.MetaTag16,
		arg.ID17,
		arg.MetaTag17,
		arg.ID18,
		arg.MetaTag18,
		arg.ID19,
		arg.MetaTag19,
		arg.ID20,
		arg.MetaTag20,
		arg.ID21,
		arg.MetaTag21,
		arg.ID22,
		arg.MetaTag22,
		arg.ID23,
		arg.MetaTag23,
		arg.ID24,
		arg.MetaTag24,
		arg.ID25,
		arg.MetaTag25,
		arg.ID26,
		arg.MetaTag26,
		arg.ID27,
		arg.MetaTag27,
		arg.ID28,
		arg.MetaTag28,
		arg.ID29,
		arg.MetaTag29,
		arg.ID30,
		arg.MetaTag30,
		arg.ID31,
		arg.MetaTag31,
		arg.ID32,
		arg.MetaTag32,
		arg.ID33,
		arg.MetaTag33,
		arg.ID34,
		arg.MetaTag34,
		arg.ID35,
		arg.MetaTag35,
		arg.ID36,
		arg.MetaTag36,
		arg.ID37,
		arg.MetaTag37,
		arg.ID38,
		arg.MetaTag38,
		arg.ID39,
		arg.MetaTag39,
		arg.ID40,
		arg.MetaTag40,
		arg.ID41,
		arg.MetaTag41,
		arg.ID42,
		arg.MetaTag42,
		arg.ID43,
		arg.MetaTag43,
		arg.ID44,
		arg.MetaTag44,
		arg.ID45,
		arg.MetaTag45,
		arg.ID46,
		arg.MetaTag46,
		arg.ID47,
		arg.MetaTag47,
		arg.ID48,
		arg.MetaTag48,
		arg.ID49,
		arg.MetaTag49,
		arg.ID50,
		arg.MetaTag50,
		arg.ID51,
		arg.MetaTag51,
		arg.ID52,
		arg.MetaTag52,
		arg.ID53,
		arg.MetaTag53,
		arg.ID54,
		arg.MetaTag54,
		arg.ID55,
		arg.MetaTag55,
		arg.ID56,
		arg.MetaTag56,
		arg.ID57,
		arg.MetaTag57,
		arg.ID58,
		arg.MetaTag58,
		arg.ID59,
		arg.MetaTag59,
		arg.ID60,
		arg.MetaTag60,
		arg.ID61,
		arg.MetaTag61,
		arg.ID62,
		arg.MetaTag62,
		arg.ID63,
		arg.MetaTag63,
		arg.ID64,
		arg.MetaTag64,
		arg.ID65,
		arg.MetaTag65,
		arg.ID66,
		arg.MetaTag66,
		arg.ID67,
		arg.MetaTag67,
		arg.ID68,
		arg.MetaTag68,
		arg.ID69,
		arg.MetaTag69,
		arg.ID70,
		arg.MetaTag70,
		arg.ID71,
		arg.MetaTag71,
		arg.ID72,
		arg.MetaTag72,
		arg.ID73,
		arg.MetaTag73,
		arg.ID74,
		arg.MetaTag74,
		arg.ID75,
		arg.MetaTag75,
		arg.ID76,
		arg.MetaTag76,
		arg.ID77,
		arg.MetaTag77,
		arg.ID78,
		arg.MetaTag78,
		arg.ID79,
		arg.MetaTag79,
		arg.ID80,
		arg.MetaTag80,
		arg.ID81,
		arg.MetaTag81,
		arg.ID82,
		arg.MetaTag82,
		arg.ID83,
		arg.MetaTag83,
		arg.ID84,
		arg.MetaTag84,
		arg.ID85,
		arg.MetaTag85,
		arg.ID86,
		arg.MetaTag86,
		arg.ID87,
		arg.MetaTag87,
		arg.ID88,
		arg.MetaTag88,
		arg.ID89,
		arg.MetaTag89,
		arg.ID90,
		arg.MetaTag90,
		arg.ID91,
		arg.MetaTag91,
		arg.ID92,
		arg.MetaTag92,
		arg.ID93,
		arg.MetaTag93,
		arg.ID94,
		arg.MetaTag94,
		arg.ID95,
		arg.MetaTag95,
		arg.ID96,
		arg.MetaTag96,
		arg.ID97,
		arg.MetaTag97,
		arg.ID98,
		arg.MetaTag98,
		arg.ID99,
		arg.MetaTag99,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var blob_id int64
		if err := rows.Scan(&blob_id); err != nil {
			return nil, err
		}
		items = append(items, blob_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlobEntriesByScopeAnd10Entries = `-- name: GetBlobEntriesByScopeAnd10Entries :many
WITH entries(id, meta_tag) AS (
  SELECT ?3 AS id, ?4 AS meta_tag
  UNION ALL SELECT ?5 AS id, ?6 AS meta_tag
  UNION ALL SELECT ?7 AS id, ?8 AS meta_tag
  UNION ALL SELECT ?9 AS id, ?10 AS meta_tag
  UNION ALL SELECT ?11 AS id, ?12 AS meta_tag
  UNION ALL SELECT ?13 AS id, ?14 AS meta_tag
  UNION ALL SELECT ?15 AS id, ?16 AS meta_tag
  UNION ALL SELECT ?17 AS id, ?18 AS meta_tag
  UNION ALL SELECT ?19 AS id, ?20 AS meta_tag
  UNION ALL SELECT ?21 AS id, ?22 AS meta_tag
)
SELECT DISTINCT be.blob_id
FROM entries e
JOIN blob_entries be
  ON be.id = e.id
 AND be.meta_tag = e.meta_tag
WHERE be.namespace = ?1
  AND be.subject = ?2
  -- Both checks are intentionally redundant: caller promises entries are all-null or all-non-null pairs.
  AND e.id IS NOT NULL
  AND e.meta_tag IS NOT NULL
`

type GetBlobEntriesByScopeAnd10EntriesParams struct {
	Namespace string  `db:"namespace"`
	Subject   int64   `db:"subject"`
	ID00      *int64  `db:"id_00"`
	MetaTag00 *string `db:"meta_tag_00"`
	ID01      *int64  `db:"id_01"`
	MetaTag01 *string `db:"meta_tag_01"`
	ID02      *int64  `db:"id_02"`
	MetaTag02 *string `db:"meta_tag_02"`
	ID03      *int64  `db:"id_03"`
	MetaTag03 *string `db:"meta_tag_03"`
	ID04      *int64  `db:"id_04"`
	MetaTag04 *string `db:"meta_tag_04"`
	ID05      *int64  `db:"id_05"`
	MetaTag05 *string `db:"meta_tag_05"`
	ID06      *int64  `db:"id_06"`
	MetaTag06 *string `db:"meta_tag_06"`
	ID07      *int64  `db:"id_07"`
	MetaTag07 *string `db:"meta_tag_07"`
	ID08      *int64  `db:"id_08"`
	MetaTag08 *string `db:"meta_tag_08"`
	ID09      *int64  `db:"id_09"`
	MetaTag09 *string `db:"meta_tag_09"`
}

func (q *Queries) GetBlobEntriesByScopeAnd10Entries(ctx context.Context, arg GetBlobEntriesByScopeAnd10EntriesParams) ([]int64, error) {
	rows, err := q.query(ctx, q.getBlobEntriesByScopeAnd10EntriesStmt, getBlobEntriesByScopeAnd10Entries,
		arg.Namespace,
		arg.Subject,
		arg.ID00,
		arg.MetaTag00,
		arg.ID01,
		arg.MetaTag01,
		arg.ID02,
		arg.MetaTag02,
		arg.ID03,
		arg.MetaTag03,
		arg.ID04,
		arg.MetaTag04,
		arg.ID05,
		arg.MetaTag05,
		arg.ID06,
		arg.MetaTag06,
		arg.ID07,
		arg.MetaTag07,
		arg.ID08,
		arg.MetaTag08,
		arg.ID09,
		arg.MetaTag09,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var blob_id int64
		if err := rows.Scan(&blob_id); err != nil {
			return nil, err
		}
		items = append(items, blob_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
