// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlstore

import (
	"context"
)

const countBlobEntriesByFilter = `-- name: CountBlobEntriesByFilter :one
SELECT COUNT(DISTINCT blob_id)
FROM blob_entries
WHERE (?1 IS NULL OR namespace = ?1)
  AND (?2 IS NULL OR subject = ?2)
  AND (?3 IS NULL OR id = ?3)
  AND (?4 IS NULL OR meta_tag = ?4)
`

type CountBlobEntriesByFilterParams struct {
	Namespace interface{} `db:"namespace"`
	Subject   interface{} `db:"subject"`
	ID        interface{} `db:"id"`
	MetaTag   interface{} `db:"meta_tag"`
}

// sqlc.narg values are nullable filter inputs, not nullable blob_entries columns.
// A nil filter field becomes `NULL IS NULL OR column = NULL`, which is TRUE,
// so that field's predicate is ignored while non-nil fields still filter normally.
func (q *Queries) CountBlobEntriesByFilter(ctx context.Context, arg CountBlobEntriesByFilterParams) (int64, error) {
	row := q.queryRow(ctx, q.countBlobEntriesByFilterStmt, countBlobEntriesByFilter,
		arg.Namespace,
		arg.Subject,
		arg.ID,
		arg.MetaTag,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBlobByBlobKey = `-- name: DeleteBlobByBlobKey :exec
DELETE FROM blobs
WHERE blob_key = ?1
`

func (q *Queries) DeleteBlobByBlobKey(ctx context.Context, blobKey string) error {
	_, err := q.exec(ctx, q.deleteBlobByBlobKeyStmt, deleteBlobByBlobKey, blobKey)
	return err
}

const deleteBlobsByFilter = `-- name: DeleteBlobsByFilter :exec
DELETE FROM blobs
WHERE blob_id IN (
    SELECT DISTINCT blob_id
    FROM blob_entries
    WHERE (?1 IS NULL OR namespace = ?1)
      AND (?2 IS NULL OR subject = ?2)
      AND (?3 IS NULL OR id = ?3)
      AND (?4 IS NULL OR meta_tag = ?4)
)
`

type DeleteBlobsByFilterParams struct {
	Namespace interface{} `db:"namespace"`
	Subject   interface{} `db:"subject"`
	ID        interface{} `db:"id"`
	MetaTag   interface{} `db:"meta_tag"`
}

func (q *Queries) DeleteBlobsByFilter(ctx context.Context, arg DeleteBlobsByFilterParams) error {
	_, err := q.exec(ctx, q.deleteBlobsByFilterStmt, deleteBlobsByFilter,
		arg.Namespace,
		arg.Subject,
		arg.ID,
		arg.MetaTag,
	)
	return err
}

const getBlobIDByBlobKey = `-- name: GetBlobIDByBlobKey :one
SELECT b.blob_id
FROM (SELECT ?1 AS blob_key) AS k
LEFT JOIN blobs b ON b.blob_key = k.blob_key
`

func (q *Queries) GetBlobIDByBlobKey(ctx context.Context, blobKey string) (*int64, error) {
	row := q.queryRow(ctx, q.getBlobIDByBlobKeyStmt, getBlobIDByBlobKey, blobKey)
	var blob_id *int64
	err := row.Scan(&blob_id)
	return blob_id, err
}

const getBlobValuesByFilter = `-- name: GetBlobValuesByFilter :many
SELECT DISTINCT b.blob_id, b.blob_key, b.blob_value
FROM blob_entries br
JOIN blobs b ON b.blob_id = br.blob_id
WHERE (?1 IS NULL OR br.namespace = ?1)
  AND (?2 IS NULL OR br.subject = ?2)
  AND (?3 IS NULL OR br.id = ?3)
  AND (?4 IS NULL OR br.meta_tag = ?4)
`

type GetBlobValuesByFilterParams struct {
	Namespace interface{} `db:"namespace"`
	Subject   interface{} `db:"subject"`
	ID        interface{} `db:"id"`
	MetaTag   interface{} `db:"meta_tag"`
}

type GetBlobValuesByFilterRow struct {
	BlobID    int64  `db:"blob_id"`
	BlobKey   string `db:"blob_key"`
	BlobValue []byte `db:"blob_value"`
}

func (q *Queries) GetBlobValuesByFilter(ctx context.Context, arg GetBlobValuesByFilterParams) ([]GetBlobValuesByFilterRow, error) {
	rows, err := q.query(ctx, q.getBlobValuesByFilterStmt, getBlobValuesByFilter,
		arg.Namespace,
		arg.Subject,
		arg.ID,
		arg.MetaTag,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlobValuesByFilterRow{}
	for rows.Next() {
		var i GetBlobValuesByFilterRow
		if err := rows.Scan(&i.BlobID, &i.BlobKey, &i.BlobValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlobValue = `-- name: UpdateBlobValue :exec
UPDATE blobs
SET blob_key = ?1,
    blob_value = ?2,
    updated_at = ?3
WHERE blob_id = ?4
`

type UpdateBlobValueParams struct {
	BlobKey   string `db:"blob_key"`
	BlobValue []byte `db:"blob_value"`
	UpdatedAt int64  `db:"updated_at"`
	BlobID    int64  `db:"blob_id"`
}

func (q *Queries) UpdateBlobValue(ctx context.Context, arg UpdateBlobValueParams) error {
	_, err := q.exec(ctx, q.updateBlobValueStmt, updateBlobValue,
		arg.BlobKey,
		arg.BlobValue,
		arg.UpdatedAt,
		arg.BlobID,
	)
	return err
}

const upsertBlob = `-- name: UpsertBlob :one
INSERT INTO blobs (
    blob_key,
    blob_value,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3
)
ON CONFLICT(blob_key) DO UPDATE SET
    blob_value = excluded.blob_value,
    updated_at = excluded.updated_at
RETURNING blob_id
`

type UpsertBlobParams struct {
	BlobKey   string `db:"blob_key"`
	BlobValue []byte `db:"blob_value"`
	UpdatedAt int64  `db:"updated_at"`
}

func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) (int64, error) {
	row := q.queryRow(ctx, q.upsertBlobStmt, upsertBlob, arg.BlobKey, arg.BlobValue, arg.UpdatedAt)
	var blob_id int64
	err := row.Scan(&blob_id)
	return blob_id, err
}
